### PR TITLE
add parsing for state files from ucs

### PR DESCRIPTION
**Pull request by thijsschnitger**
This change allows tfstate files generated by https://github.com/CiscoCloud/terraform-provider-ucs to be translated to Ansible inventory.

### CODE REVIEW

**Comment by siddharthist** [comment]
@thijsschnitger I can't see the repo you linked to, is it private?

**Comment by thijsschnitger** [comment]
The repo is indeed private for now, but you should have access to it by now. 
I'll add the unit test as soon as I can.

**Comment by thijsschnitger** [comment]
@siddharthist please let me know if this is sufficient.

**Comment by siddharthist** [comment]
@thijsschnitger Your branch is now out of date with master :cry: @BrianHicks can you review?

**Comment by siddharthist** [comment]
Ping @BrianHicks for review

**Comment by BrianHicks** [comment]
LGTM, thanks @thijsschnitger

**Pull request merged**
